CREATE TABLE Users (
    UserID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    UserName VARCHAR(20) NOT NULL UNIQUE,
    Password VARCHAR(20) NOT NULL
);

CREATE TABLE User_Statistics(
    UserID INT NOT NULL PRIMARY KEY,
    No_of_Sessions INT DEFAULT 0,
    Time INT DEFAULT 0,
    No_Of_Wins INT DEFAULT 0,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE 
);

CREATE TABLE Items(
    ItemID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Item_Name VARCHAR(255) NOT NULL
);

CREATE TABLE Sessions(
    SessionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Time INT NOT NULL,
    ItemID INT,
    Win TINYINT(1),
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES Items(ItemID) ON DELETE CASCADE
);
